### ISSUE TITLE
import convert from 'xml-js';

### ISSUE THREAD

**Issue by firstlevelIT** [enricodeleo/fattura24#7]
usando node v10.16.3 con l'esempio ho questo strano errore

node test-key.js

import convert from 'xml-js';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/steve/fattura24/example/test-key.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by enricodeleo** [comment]
Se il tuo runtime non supporta `import` (e dunque i file `.mjs`) devi adottare un transpiler. Questo stesso progetto usa Babel per questo scopo.
